default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # http://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  user: derik
  password: '123'

development:
  <<: *default
  database: one_bit_tweeter

test:
  <<: *default
  database: one_bit_tweeter_test

#
# production:
#   <<: *default
#   database: OneBitTwitter_production
#   username: OneBitTwitter
#   password: <%= ENV['ONEBITTWITTER_DATABASE_PASSWORD'] %>
